// Generated by CoffeeScript 1.6.3
var axon, handler, server;

axon = require('axon');

server = null;

handler = function(message) {
  return console.log(message);
};

exports.listen = function(port) {
  if (server !== null) {
    throw new Error("Panacea: server is already listening");
  }
  server = axon.socket('pull');
  server.format('json');
  server.bind(port);
  server.on('message', handler);
  return this;
};
